export const LINKS = {
	REACT: 'https://react.dev/',
	REACT_NATIVE: 'https://reactnative.dev/',
	TYPESCRIPT: 'https://www.typescriptlang.org/',
	EASY_PEASY: 'https://easy-peasy.vercel.app/',
	REDUX: 'https://redux.js.org/',
	NEXT: 'https://nextjs.org/',
	NODE: 'https://nodejs.org/en/',
	NEST: 'https://nestjs.com/',
	POSTGRESQL: 'https://www.postgresql.org/',
	KNEX: 'https://knexjs.org/',
	DOCKER: 'https://www.docker.com/',
	DISCORD: 'https://discord.com/developers/docs/intro',
	SOLIDITY: 'https://soliditylang.org/',
	STRAPI: 'https://strapi.io/',
	LARAVEL: 'https://laravel.com/',
	EXPO: 'https://expo.dev/',
	BLOCKFROST: 'https://blockfrost.io/',
	ALCHEMY: 'https://www.alchemy.com/',
	WEB3: 'https://web3js.org/',
	SHOPIFY: 'https://shopify.dev/',
}
