import type { NextPage } from 'next'
import Head from 'next/head'

import { Hero } from '../components/landing'
import { Projects } from '../components/landing/projects/Projects'
import { Layout } from '../components/shared'

const Landing: NextPage = () => {
    return (
        <Layout>
            <Head>
                <title>Brendan Hemat-Siraky</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Projects />
        </Layout>
    )
}

export async function getStaticProps() {
    return {
        props: {

        },
    }
}

export default Landing