import type { NextPage } from 'next'
import Head from 'next/head'

import ReactFullpage from '@fullpage/react-fullpage'

import { Projects } from '../components/landing/projects/Projects'
import { LandingContext } from '../model/context/LandingContext'
import { fetchLanding } from '../api/fetchLanding'
import { Me } from '../components/landing/me/Me'
import { Layout } from '../components/shared'
import { Hero } from '../components/landing'
import { Landing } from '../types/Landing'

const Landing: NextPage<Landing> = (landing) => {
    return (
        <LandingContext.Provider value={landing}>
            <Layout>
                <Head>
                    <title>Brendan Hemat-Siraky</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <ReactFullpage
                    licenseKey={process.env.FULLPAGE_LICENSE_KEY || ''}
                    showActiveTooltip={false}
                    navigation={true}
                    
                    render={() => {
                        return (
                            <ReactFullpage.Wrapper>
                                {[Hero, Me, Projects].map(Component => (
                                    <div className="section">
                                        <Component />
                                    </div>
                                ))}
                            </ReactFullpage.Wrapper>
                        )
                    }}
                />
            </Layout>
        </LandingContext.Provider>
    )
}

export async function getStaticProps() {
    const landing = await fetchLanding()

    return {
        props: {
            ...landing
        },
    }
}

export default Landing