import type { NextPage } from 'next'
import Head from 'next/head'

import { Projects } from '../components/landing/projects/Projects'
import { LandingContext } from '../model/context/LandingContext'
import { fetchLanding } from '../api/fetchLanding'
import { Layout } from '../components/shared'
import { Hero } from '../components/landing'
import { Landing } from '../types/Landing'
import { Me } from '../components/landing/me/Me'

const Landing: NextPage<Landing> = (landing) => {
    return (
        <LandingContext.Provider value={landing}>
            <Layout>
                <Head>
                    <title>Brendan Hemat-Siraky</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Hero />
                <Me />
                <Projects />
            </Layout>
        </LandingContext.Provider>
    )
}

export async function getStaticProps() {
    const landing = await fetchLanding()

    return {
        props: {
            ...landing
        },
    }
}

export default Landing